### ISSUE TITLE
Allow a periodic table based on the discovery date

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/moocs#3]

**Comment by lpatiny** [comment]
The dates have been added in the google docs. We should take care than some of them are <0 and some of them are ~.
I think that when <0 we should some how ignore them for the slider selection tool and but in the table BC or a translation in french ?

**Comment by stropitek** [comment]
See https://my.cheminfo.org/?v=HEAD&direct=true&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F3e54b136946b03d66fc7e7e64b63d694%2Fview.json

The admin layer allows you to customize what properties are available for the slider
